# Generated by Django 4.1.4 on 2022-12-18 11:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuaid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("slug", models.SlugField(max_length=63, unique=True)),
                ("ticker", models.CharField(max_length=31)),
                ("total", models.IntegerField(default=0)),
                ("initial_price", models.FloatField(default=0)),
                ("current_price", models.FloatField(default=0)),
                ("gain", models.FloatField(default=0)),
                ("current_value", models.FloatField(default=0)),
                ("initial_value", models.FloatField(default=0)),
                ("initial_weight", models.FloatField(default=0)),
                ("current_weight", models.FloatField(default=0)),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
        ),
    ]
