# Generated by Django 4.1.4 on 2023-01-01 19:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dividend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuoid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("slug", models.SlugField(max_length=63, unique=True)),
                ("date", models.DateTimeField()),
                ("per_share", models.FloatField()),
                ("value", models.FloatField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dividends",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
