# Generated by Django 4.1.4 on 2022-12-14 18:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("portfolios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uutid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                ("slug", models.SlugField(max_length=63, unique=True)),
                ("ticker", models.CharField(max_length=31)),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "Buy"), (1, "Sell")],
                        verbose_name="transaction type",
                    ),
                ),
                ("price", models.FloatField()),
                ("amount", models.IntegerField()),
                ("provision", models.FloatField()),
                ("date", models.DateField()),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="portfolios.portfolio",
                    ),
                ),
            ],
        ),
    ]
